version: '3'

services:
  responser_keycloak_db:
    container_name: responser_keycloak_db
    build: ./responser-keycloak/database
    ports:
      - "5433:5432"
    volumes:
      - .local/responser_keycloak_db/:/var/lib/postgresql/data
  responser_keycloak_server:
    container_name: responser_keycloak_server
    build: ./responser-keycloak/auth-server
    command:
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.migration.usersExportStrategy=realm_file"
    ports:
      - "8081:8080"
    volumes:
      - .local/responser_keycloak/:/opt/jboss/keycloak/standalone/data/
  responser_db:
    container_name: responser_db
    build: ./responser-backend/database
    ports:
      - "5432:5432"
    volumes:
      - .local/responser_db/:/var/lib/postgresql/data