version: '3'

services:
  responser_db:
    container_name: responser_db
    build: ./responser-backend/database
    ports:
      - "5432:5432"
    volumes:
      - .local/responser_db/:/var/lib/postgresql/data