server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/responser
    username: postgres
    password: root
    testWhileIdle: 'true'
    validationQuery: SELECT 1
  sql:
    init:
      platform: postgres
responser:
  auth:
    registrationPageUrl: http://127.0.0.1:3000/sign-up
    afterLogoutUrl: http://127.0.0.1:3000
    noSessionRedirectUrl: http://localhost:1234
    clientCredentials:
      -
        clientId: responser-web-client
        clientSecret: responser-web-client-secret
        redirectUri: http://127.0.0.1:3000/auth-code
    allowedOrigins:
      - http://127.0.0.1:3000