server:
  port: 8081
  servlet:
    context-path: /auth
  error:
    include-binding-errors: always
    include-message: always
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.security: trace
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewly
    username: postgres
    password: root
    testWhileIdle: 'true'
    validationQuery: SELECT 1
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: some-google-id
            client-secret: some-google-secret
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  mail:
    host: smtp.office365.com
    port: 587
    username: some@user.name
    password: "PAAAASWORD"
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true

reviewly:
  selfHost: http://local-dev-reviewly.space
  frontendAppUrl: ${reviewly.selfHost}/app
  registrationPageUrl: ${reviewly.frontendAppUrl}/sign-up
  forgotPasswordPageUrl: ${reviewly.frontendAppUrl}/forgot-password
  noReplyEmail: no-reply@reviewly.space
  contactEmail: contact@reviewly.space
  clientCredentials:
    -
      clientId: reviewly-web-client
      clientSecret: "{noop}reviewly-web-client-secret"
      redirectUri: ${reviewly.frontendAppUrl}/auth-code
  allowedOrigins:
    - ${reviewly.selfHost}
