server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
logging:
  level:
    root: info
    sql: warn
    web: info
  file:
    name: .local/logs/backend/reviewly-logs.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 3MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewly
    username: postgres
    password: root
    testWhileIdle: 'true'
    validationQuery: SELECT 1
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://local-dev-reviewly.space/auth
  cloud:
    aws:
      region:
        static: us-east-1
      endpoint: http://localhost:9000
      s3:
        path-style-access-enabled: true
      credentials:
        access-key: some-access-key
        secret-key: some-secret-key
  mail:
    host: smtp.office365.com
    port: 587
    username: some@user.name
    password: "PAAAASWORD"
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
reviewly:
  runMode: LOCAL
  selfHost: http://local-dev-reviewly.space
  feApplicationUrl: ${reviewly.selfHost}/app
  authApplicationUrl: ${reviewly.selfHost}/auth
  authLoginPageUrl: ${reviewly.authApplicationUrl}/oauth2/authorize
  authLogoutPageUrl: ${reviewly.authApplicationUrl}/logout
  authRedirectUri: ${reviewly.feApplicationUrl}/auth-code
  signUpPageUrl: ${reviewly.feApplicationUrl}/sign-up
  profilePageUrl: ${reviewly.feApplicationUrl}/main
  restorePasswordPageUrl: ${reviewly.feApplicationUrl}/restore-password
  clientId: reviewly-web-client
  clientSecret: reviewly-web-client-secret
  downloadExtensionChrome: https://www.google.com
  chromeExtensionId: bcgepbhdoibfdnpmemhdjifmjdmfacml
  noReplyEmail: no-reply@reviewly.space
  contactEmail: contact@reviewly.space
  fileStorageUrl: ${reviewly.selfHost}/cdn
  fileStorageBucket: reviewly-dev
  fileStorageBucketSitesIcons: sites-icons
  fileStorageBucketUsersAvatars: users-avatars
  fileStorageUrlSitesIcons: ${reviewly.fileStorageUrl}/${reviewly.fileStorageBucketSitesIcons}
  fileStorageUrlUsersAvatars: ${reviewly.fileStorageUrl}/${reviewly.fileStorageBucketUsersAvatars}
  defaultUserAvatarFileName: default_avatar.png
  defaultSiteIconFileName: default_site_icon.png
  allowedOrigins:
    - ${reviewly.selfHost}
    - chrome-extension://${reviewly.chromeExtensionId}
