server:
  port: 8080
logging:
  level:
    root: info
    sql: warn
    web: info
  file:
    name: /application/logs/reviewly-logs.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://responser-db:5432/responser
    username: postgres
    password: root
    testWhileIdle: 'true'
    validationQuery: SELECT 1
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://dev-auth.reviewly.space
  mail:
    host: smtpout.secureserver.net
    port: 465
    username: info@reviewly.space
    password: 5#OFpkKn9YXa69Dl6Ts5&q6Z
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.trust: "*"
responser:
  api:
    runMode: DEV
    selfHost: http://dev-api.reviewly.space
    feApplicationUrl: http://dev-app.reviewly.space
    responserInfoEmail: info@reviewly.space
    mockEmail: evgeniionegin791@gmail.com
    allowedOrigins:
      - http://dev-app.reviewly.space
      - chrome-extension://bcgepbhdoibfdnpmemhdjifmjdmfacml
