server:
  port: 8080
logging:
  level:
    root: info
    sql: warn
    web: info
  file:
    name: /application/logs/reviewly-logs.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: 'true'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://responser-db:5432/responser
    username: postgres
    password: root
    testWhileIdle: 'true'
    validationQuery: SELECT 1
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://dev.reviewly.space/auth
  mail:
    host: smtpout.secureserver.net
    port: 465
    username: info@reviewly.space
    password: 5#OFpkKn9YXa69Dl6Ts5&q6Z
    protocol: smtp
    properties.mail.smtp:
      auth: true
      ssl.enable: true
      ssl.trust: "*"
responser:
  runMode: LOCAL
  selfHost: http://dev.reviewly.space
  feApplicationUrl: ${responser.selfHost}/app
  authApplicationUrl: ${responser.selfHost}/auth
  authLoginPageUrl: ${responser.authApplicationUrl}/oauth2/authorize
  authLogoutPageUrl: ${responser.authApplicationUrl}/logout
  authRedirectUri: ${responser.feApplicationUrl}/auth-code
  signUpPageUrl: ${responser.feApplicationUrl}/app/sign-up
  clientId: responser-web-client
  clientSecret: responser-web-client-secret
  downloadExtensionChrome: https://www.google.com
  chromeExtensionId: bcgepbhdoibfdnpmemhdjifmjdmfacml
  responserInfoEmail: info@reviewly.space
  allowedOrigins:
    - ${responser.selfHost}
    - chrome-extension://bcgepbhdoibfdnpmemhdjifmjdmfacml
